import { 
    IonHeader, 
    IonToolbar, 
    IonContent, 
    IonButton,
    IonRouterOutlet,
    IonApp,
    IonList,
    IonIcon,
    IonItem,
    IonLabel,
    IonPopover,
    IonRippleEffect,
    IonReorder,
    IonReorderGroup,
    IonAccordion,
    IonAccordionGroup,
    IonRadio,
    IonFab,
    IonFabButton,
    IonRow,
    IonSegmentButton,
    IonSelect,
    IonSelectOption,
    IonToggle,
    IonListHeader,
    IonCol,
    IonSpinner,
    IonText,
    IonThumbnail,
    IonInput,
    IonSegment,
    IonCheckbox
 } from '@ionic/angular/standalone';
import { 
  DecimalPipe, 
  DatePipe, 
  AsyncPipe, 
  NgClass, 
  NgStyle,
  UpperCasePipe
} from '@angular/common';

export const IONIC_COMPONENTS = [
  IonHeader,
  IonToolbar,
  IonContent,
  IonButton,
  IonRouterOutlet,
  IonApp,
  IonList,
  IonIcon,
  IonItem,
  IonLabel,
  IonPopover,
  IonRippleEffect,
  IonReorder,
  IonReorderGroup,
  IonAccordion,
  IonAccordionGroup,
  IonRadio,
  IonFab,
  IonFabButton,
  IonRow,
  IonToggle,
  IonListHeader,
  IonSegmentButton,
  IonSelect,
  IonSelectOption,
  IonCol,
  IonSpinner,
  IonText,
  IonThumbnail,
  IonInput,
  IonSegment,
  IonCheckbox
] as const;
 export const ANGULAR_COMMON = [
  DecimalPipe, 
  DatePipe, 
  UpperCasePipe, 
  AsyncPipe, 
  NgClass, 
  NgStyle
] as const;